[build]
  command = "npm run prisma:generate && npm run build"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/**,README.md,docs/**,.env.example,package-lock.json"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL,NEXT_PUBLIC_SUPABASE_URL,APP_MODE,ADMIN_EMAIL,NODE_VERSION,NEXTAUTH_URL"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
